################################################################################
#
# install_h.mk
#
ifdef RNMAKE_DOXY
/*! 
\file 

\brief Auto-generate the install.h include file for the specific package
       architecture.

DEPRECATED.

\par Usage:
make pkgroot=\<dir\> install_h=\<file\> arch=\<arch\>
     bindir=\<bindir\> sbindir=\<sbindir\> libdir=\<libdir\>
     includedir=\<includedir\> sysconfdir=\<sysconfdir\> docdir=\<docdir\>
     mandir=\<mandir\> infodir=\<infodir\>

\pkgsynopsis
RN Make System

\pkgfile{install_h.mk}

\pkgauthor{Robin Knight,robin.knight@roadnarrows.com}

\pkgcopyright{2005-2018,RoadNarrows LLC,http://www.roadnarrows.com}

\LegalBegin
Copyright (c) 2005-2020 RoadNarrows LLC

Licensed under the MIT License (the "License").

You may not use this file except in compliance with the License. You may
obtain a copy of the License at:

https://opensource.org/licenses/MIT

The software is provided "AS IS", without warranty of any kind, express or
implied, including but not limited to the warranties of merchantability,
fitness for a particular purpose and noninfringement. in no event shall the
authors or copyright holders be liable for any claim, damages or other
liability, whether in an action of contract, tort or otherwise, arising from,
out of or in connection with the software or the use or other dealings in the
software.
\LegalEnd

\cond RNMAKE_DOXY
 */
endif
#
################################################################################

_INSTALL_H_MK = 1

$(install_h):
	@echo ''
	@echo '     $@'
	@echo '//' > $@
	@echo '// File: $(notdir $@)' >> $@
	@echo '//' >> $@
	@echo '/*!' >> $@
	@echo	' * \\file' >> $@
	@echo	' *' >> $@
	@echo	' * \\brief Package installation information.' >> $@
	@echo	' *' >> $@
	@echo ' * \\par Architecture: ' >> $@
	@echo ' * $(arch)' >> $@
	@echo	' *' >> $@
	@echo ' * \warning Auto-generated by Rules.mk on' `date`>> $@
	@echo	' *' >> $@
	@echo ' * \\par Copyright:' >> $@
	@echo ' * \\n All Rights Reserved' >> $@
	@echo ' */' >> $@
	@echo '#ifndef _INSTALL_H' >> $@
	@echo '#define _INSTALL_H' >> $@
	@echo '' >> $@
	@echo '/*! \\brief package install bin directory*/'    							>> $@
	@echo '#define PKG_INSTALL_BINDIR      "$(bindir)"'     						>> $@
	@echo '' >> $@
	@echo '/*! \\brief package install system bin directory */' 				>> $@
	@echo '#define PKG_INSTALL_SBINDIR     "$(sbindir)"'    						>> $@
	@echo '' >> $@
	@echo '/*! \\brief package install include directory */'            >> $@
	@echo '#define PKG_INSTALL_INCDIR      "$(includedir)"' 						>> $@
	@echo '' >> $@
	@echo '/*! \\brief package library directory */'                		>> $@
	@echo '#define PKG_INSTALL_LIBDIR      "$(libdir)"'     					 	>> $@
	@echo '' >> $@
	@echo '/*! \\brief package install system configuration directory */'>> $@
	@echo '#define PKG_INSTALL_SYSCONFDIR  "$(sysconfdir)"' 						>> $@
	@echo '' >> $@
	@echo '/*! \\brief package install documentation directory */'      >> $@
	@echo '#define PKG_INSTALL_DOCDIR      "$(docdir)"'     						>> $@
	@echo '' >> $@
	@echo '/*! \\brief package install man pages directory */'          >> $@
	@echo '#define PKG_INSTALL_MANDIR      "$(mandir)"'     						>> $@
	@echo '' >> $@
	@echo '/*! \\brief package install information directory (s) */'    >> $@
	@echo '#define PKG_INSTALL_INFODIR     "$(infodir)"'    						>> $@
	@echo '' >> $@
	@echo '#endif // _INSTALL_H' >> $@

ifdef RNMAKE_DOXY
/*! \endcond RNMAKE_DOXY */
endif
