#!/bin/sh

# This script will create links, et c. after a package has been installed

set -e
# Automatically added by dh_installdocs
#if [ "$1" = "configure" ]; then
# if [ -d /usr/doc -a ! -e /usr/doc/parted -a -d /usr/share/doc/parted ]; then
#   ln -sf ../share/doc/parted /usr/doc/parted
# fi
#fi

#ADD ADDITIONAL TASKS HERE 
#  (e.g. adding a library dir to /etc/ld.so.conf.d/rnr.conf)
#  echo @PREFIX@/lib/rnr >> /etc/ld.so.conf.d/rnr.conf

ldconfig

ln -s @RT_PREFIX@/share/@PKG_NAME@-@RT_VERSION@ @RT_PREFIX@/share/$PKG_NAME@
# End automatically added section
