#!/usr/bin/env python3
#
# @PKG_NAME@ python modules setup.py script.
#
# Auto-generated by the rnmake system @THIS_DATE@ @THIS_TIME@
#
# \LegalBegin
# \LegalEnd
#

import os
import sys
from setuptools import setup, find_packages

# Package Information (required by setup and rnmake utilities)
PkgInfo = {
    'name':     '@PKG_NAME@',
    'version':  '@PKG_VER@',

    'packages': find_packages(exclude=['testing']),
    'scripts':  [],

    # Project uses reStructuredText, so ensure that the docutils get
    # installed or upgraded on the target machine
    #install_requires=["docutils>=0.3"],

    'package_data': {
      '@PKG_NAME@': ['README.md', 'images'],
      '@PKG_NAME@.images': ['*.png', '*.jpg', '*.tiff', '*.svg'],
      '@PKG_NAME@.pleistocene': ['_*.so'],
    },

    # metadata to display on PyPI
    'author':       '@PKG_AUTHOR@',
    'author_email': '@PKG_EMAIL@',
    'description':  '@PKG_DESC@.',
    'keywords':     '@PKG_KW@',
    'url':          '@ORG_URL@',
    'project_urls': {
        'Bug Tracker':    'https://bugs.good.bce/musteat',
        'Documentation':  '@PKG_URL@.wiki',
        'Source Code':    '@PKG_URL@',
    },
    'classifiers': [
        '@PKG_LICENSE@ License',
    ],

    'license': '@PKG_LICENSE@',

    'long_description':  """\
ADD
LONG
DESCRIPTION
HERE
""",

    # could also include download_url, etc.
}

## run
if __name__ == "__main__":
  setup(**PkgInfo)
